calendario/routes.py
from flask import(render_template, Blueprint, flash, g, redirect, request, session,url_for,send_file,Response,make_response)
from werkzeug.utils import secure_filename
from dateutil import parser
from user.models.user import User
from calendario.models.empresa import Empresa
from calendario.models.calendario import Calendario
from calendario.models.comunidad import Comunidad
from calendario.models.localidad import Localidad
from calendario.models.festivocom import Festivocom
from calendario.models.festivoloc import Festivoloc
from sqlalchemy.orm import aliased

from sqlalchemy import text, func, and_ , or_

from reportlab.lib import colors
from fpdf import FPDF
from io import BytesIO

from user.routes import login_required
from datetime import date, timedelta, datetime
import calendar
from main import db, app
import os, json
import locale
import pandas as pd
from forms import fempresas
from forms import fcalendario

calendario = Blueprint('calendario', __name__, template_folder='templates', url_prefix='/calendario')

lang_code =  'es'

@calendario.route('/calendarios')
def calendarios():
    return redirect(url_for('index'))

@calendario.route('/')
@login_required
def inicio():
    
    # Comprobamos si hay calendario
    calendario = Calendario.query.count()
    empresas = Empresa.query.count()
    comunidades = Comunidad.query.count()
    localidades = Localidad.query.count()
    festivocom = Festivocom.query.count()
    festivoloc = Festivoloc.query.count()

    form = fcalendario()

    if calendario > 0:
        datos = {'calendario' : calendario,'empresas':empresas,'comunidades':comunidades,'localidades':localidades,'festivocom':festivocom,'festivoloc':festivoloc}
    else:
        datos = {'calendario' : calendario,'empresas':empresas,'comunidades':comunidades,'localidades':localidades,'festivocom':festivocom,'festivoloc':festivoloc}

    return render_template('calendario/inicio.html',datos = datos,form=form)

@calendario.route('/comunidad/<id>')
@login_required
def comunidad(id):
    localidades = Localidad.query.filter(Localidad.comunidad_id == id)
    comunidad = Comunidad.query.get(id)
    return render_template('calendario/comunidad.html',localidades = localidades, comunidad = comunidad)

@calendario.route('/empresa_cal/<empresa_id>')
@login_required
def empresa_cal(empresa_id):
    empresa = Empresa.query.get(empresa_id)
    loc = empresa.localidad_id
    com = empresa.localidad.comunidad_id
    festivoscom = Festivocom.query.filter(Festivocom.comunidad_id == com).all()
    festivosloc = Festivoloc.query.filter(Festivoloc.localidad_id == loc)
    mitadc = len(festivoscom) // 2
    com_iz = festivoscom[:mitadc+1]
    com_de = festivoscom[mitadc+1:]
    datos = [get_calendar(1,2024,loc,com),get_calendar(2,2024,loc,com),get_calendar(3,2024,loc,com),
             get_calendar(4,2024,loc,com),get_calendar(5,2024,loc,com),get_calendar(6,2024,loc,com),
             get_calendar(7,2024,loc,com),get_calendar(8,2024,loc,com),get_calendar(9,2024,loc,com),
             get_calendar(10,2024,loc,com),get_calendar(11,2024,loc,com),get_calendar(12,2024,loc,com)]
    return render_template('calendario/empresa_cal.html',com_iz=com_iz,com_de=com_de,empresa = empresa,datos=datos,festivoscom=festivoscom,festivosloc=festivosloc)

@calendario.route('/comunidad')
@login_required
def comunidades():
    localidades = Localidad.query.order_by(Localidad.id).all()
    return render_template('calendario/comunidades.html',localidades = localidades)


@calendario.route('/empresa/<id>')
@login_required
def empresa(id):
    empresas = Empresa.query.filter(Empresa.localidad.has(Localidad.comunidad_id == id))
    comunidad = Comunidad.query.get(id)
    return render_template('calendario/empresa.html',empresas = empresas, comunidad = comunidad)

@calendario.route('/empresas')
def empresas():
    #return "Enlace correcto"
    empresas = Empresa.query.all()

    return render_template('calendario/empresas.html',empresas=empresas)

@calendario.route('/festcom/')
@login_required
def festcom():
    festivoscomunitarios = Festivocom.query.all()
    if festivoscomunitarios:
        meses = ('enero','febrero','marzo','abril','mayo','junio','julio','agosto','septiembre','octubre','noviembre','diciembre')
        cal = {'enero':get_calendar(1,2024,11,10),'febrero':get_calendar(2,2024,11,10),'marzo':get_calendar(3,2024,11,10),
            'abril':get_calendar(4,2024,11,10),'mayo':get_calendar(5,2024,11,10),'junio':get_calendar(6,2024,11,10),
            'julio':get_calendar(7,2024,11,10),'agosto':get_calendar(8,2024,11,10),'septiembre':get_calendar(9,2024,11,10),
            'octubre':get_calendar(10,2024,11,10),'noviembre':get_calendar(11,2024,11,10),'diciembre':get_calendar(12,2024,11,10)}
        #print(cal['febrero'])
    else:
        festivoscomunitarios, meses, cal = '','',''
    return render_template('calendario/festcom.html',festivoscomunitarios = festivoscomunitarios,meses=meses,cal = cal)

# Lista de días festivos por localidades
@calendario.route('/festloc')
@login_required
def festloc():
    festivoslocales = Festivoloc.query.all()
    if festivoslocales:
        meses = ('enero','febrero','marzo','abril','mayo','junio','julio','agosto','septiembre','octubre','noviembre','diciembre')
        cal = {'enero':get_calendar(1,2024,11,10),'febrero':get_calendar(2,2024,11,10),'marzo':get_calendar(3,2024,11,10),
            'abril':get_calendar(4,2024,11,10),'mayo':get_calendar(5,2024,11,10),'junio':get_calendar(6,2024,11,10),
            'julio':get_calendar(7,2024,11,10),'agosto':get_calendar(8,2024,11,10),'septiembre':get_calendar(9,2024,11,10),
            'octubre':get_calendar(10,2024,11,10),'noviembre':get_calendar(11,2024,11,10),'diciembre':get_calendar(12,2024,11,10)}
    else:
        festivoslocales, meses, cal = '','',''
    return render_template('calendario/festloc.html',festivoslocales = festivoslocales,meses=meses,cal = cal)


@calendario.route('/dias/',methods = ['POST'])
@login_required
def dias():
    form = fcalendario()
    year = request.form['year']
    
    #locale.setlocale(locale.LC_TIME, 'es_ES')
    fecha_inicial = year + "-01-01"
    fecha_final = year + "-12-31"
    fecha_inicial_obj = date.fromisoformat(fecha_inicial)
    fecha_final_obj = date.fromisoformat(fecha_final)

    # Verifica que la fecha inicial sea anterior a la fecha final
    if fecha_inicial_obj > fecha_final_obj:
        return "Error: La fecha inicial debe ser anterior a la fecha final."

    # Genera una lista de todas las fechas correlativas dentro del rango especificado
    all_dates = []
    current_date = fecha_inicial_obj
    while current_date <= fecha_final_obj:
        fecha = str(current_date)
        fecha2 = parser.parse(fecha)  # Convierte la cadena de fecha a un objeto datetime
        weekday = fecha2.weekday()
        semana = fecha2.isocalendar()[1]
        ejercicio = fecha[0:4]
        mes = fecha[5:7]
        mes2 = str(current_date.month)
        nombre_mes = str(calendar.month_name[current_date.month])
        dia = fecha[8:]
        dia2 = str(current_date.day)
        if mes in ['01','02','03']:
            trimestre = "1"
        elif mes in ['04','05','06']:
            trimestre = '2'
        elif mes in ['07','08','09']:
            trimestre = '3'
        else:
            trimestre = '4'
        all_dates.append(Calendario(fecha=current_date, ejercicio=ejercicio, mes=mes,mes2=mes2,nombre_mes= nombre_mes, dia=dia, dia2=dia2, trimestre=trimestre, semana = semana, weekday = weekday))
        current_date += timedelta(days=1)

    # Inserta las fechas en la tabla de la base de datos
    db.session.bulk_save_objects(all_dates)
    db.session.commit()

    return f"Se generaron y almacenaron {len(all_dates)} días correlativos en la base de datos."

def resumen_excel():
    data = 'calendario/static/excel/calendario.xlsx'
    ruta = 'calendario/static/excel'
    fichero = 'calendario.xlsx'

    ruta_archivo = os.path.join(app.root_path, ruta, fichero)

    if os.path.exists(ruta_archivo):

        empresas = pd.read_excel(data,sheet_name="Empresas", names=['Empresa','Domicilio','Actividad','Convenio','Centro','Localidad'])
        empresas[['localidad_id', 'localidad']] = empresas['Localidad'].str.split('-', expand=True)
        empresas = empresas.fillna('')
        emp = len(empresas)

        localidades = pd.read_excel(data,sheet_name="Localidades")
        localidades.columns = ['id','localidad','cod_localidad','cod_comunidad','descripcion']
        localidades[['comunidad_id', 'comunidad']] = localidades['cod_comunidad'].str.split('-', expand=True)
        localidades = localidades.fillna('')
        loc = len(localidades)
        
        fesloc = pd.read_excel(data,sheet_name="Festivos_Localidades")
        fesloc.columns = ['id','fecha','nombre','descripcion','id_localidad']
        fesloc[['localidad_id', 'localidad']] = fesloc['id_localidad'].str.split('-', expand=True)
        fesloc = fesloc.fillna('')
        floc = len(fesloc)

        fescom = pd.read_excel(data,sheet_name="Festivos_Comunidades")
        fescom.columns = ['id','fecha','nombre','descripcion','id_comunidad']
        fescom[['comunidad_id', 'comunidad']] = fescom['id_comunidad'].str.split('-', expand=True)
        fescom = fescom.fillna('')
        fcom = len(fescom)

        resumen = {'fcom':fcom,'floc':floc,'loc':loc,'emp':emp}
    else: 
        resumen = {'fcom':0,'floc':0,'loc':0,'emp':0}
    return resumen

@calendario.route('/datos/',methods = ['GET','POST'])
def datos():
    if request.method == 'POST':
        fichero = request.files['fichero']
        if fichero:
            form = fempresas()
            
            # Hacer algo con el archivo, por ejemplo, guardarlo en el servidor
            filepath = os.path.abspath('calendario/static/excel/calendario.xlsx')
            fichero.save(filepath)

            resumen = resumen_excel()

calendario/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Calendarios Laborales</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}">
</head>

<body>

    <body class="contenedor">
        <div id="mini-nav">
            <div id="mini-logo">Tla Corp - Calendarios</div>
            <div id="mini-menu">
                <ul>
                    <li><a href="">Login</a></li>
                    <li><a href="">Sign Up</a></li>
                </ul>
            </div>
        </div>
        <div id="maxi-logo">
            <img src="{{ url_for('static', filename='img/logo_100.png') }}" alt="">
        </div>
        <div id="maxi-menu">
            <ul>
                <li><a href="{{url_for('calendario.inicio')}}">Home</a></li>
                <li><a href="{{url_for('calendario.inicio')}}">Calendarios</a></li>
                <li><a href="">Control horario</a></li>
            </ul>
        </div>
        <div id="lside">
            {% block lside %}{% endblock %}
            <h5 class="lside-cab">Calendario laboral</h5>
            <h5 class="lside-cab2">Empresas</h5>
            <ul class="lside-ul">
                <li><a href="{{url_for('calendario.empresas')}}">Todas</a></li>
            {% for comunidad in leftside_queries['comuni'] %}
                <li><a href="{{url_for('calendario.empresa',id = comunidad.id)}}">{{ comunidad.nombre }}</a></li>
            {% endfor %}
            </ul>
            <h5 class="lside-cab2">Eventos</h5>
            <ul class="lside-ul">
                <li><a href="{{url_for('calendario.festcom')}}">Festivos Comunidad</a></li>
                <li><a href="{{url_for('calendario.festloc')}}">Festivos locales</a></li>
            </ul>
            <h5 class="lside-cab2">Localidades</h5>
            <ul class="lside-ul">
                <li><a href="{{url_for('calendario.comunidades')}}">Todas</a></li>
                {% for comunidad in leftside_queries['comuni'] %}
                <li><a href="{{url_for('calendario.comunidad', id = comunidad.id)}}">{{ comunidad.nombre }}</a></li>
                {% endfor %}
            </ul>
            <h5 class="lside-cab2">Configuración</h5>
            <ul class="lside-ul">
                <li><a href="{{url_for('calendario.datos')}}">Importar datos</a></li>
                <li><a href="{{url_for('calendario.reset')}}">Reset</a></li>
            </ul>

        </div>
        <div id="rside">
            {% block rside %}{% endblock %}
        </div>
        <div id="pie">
            <div id="links">
                <svg class="icon-map" xmlns="http://www.w3.org/2000/svg"
                    viewBox="0 0 576 512">
                    <path
                        d="M408 120c0 54.6-73.1 151.9-105.2 192c-7.7 9.6-22 9.6-29.6 0C241.1 271.9 168 174.6 168 120C168 53.7 221.7 0 288 0s120 53.7 120 120zm8 80.4c3.5-6.9 6.7-13.8 9.6-20.6c.5-1.2 1-2.5 1.5-3.7l116-46.4C558.9 123.4 576 135 576 152V422.8c0 9.8-6 18.6-15.1 22.3L416 503V200.4zM137.6 138.3c2.4 14.1 7.2 28.3 12.8 41.5c2.9 6.8 6.1 13.7 9.6 20.6V451.8L32.9 502.7C17.1 509 0 497.4 0 480.4V209.6c0-9.8 6-18.6 15.1-22.3l122.6-49zM327.8 332c13.9-17.4 35.7-45.7 56.2-77V504.3L192 449.4V255c20.5 31.3 42.3 59.6 56.2 77c20.5 25.6 59.1 25.6 79.6 0zM288 152a40 40 0 1 0 0-80 40 40 0 1 0 0 80z" />
                </svg>
                <span class="espacio">Ubicación</span>
                &nbsp;
                <svg class="icon-phone" xmlns="http://www.w3.org/2000/svg"  viewBox="0 0 512 512">
                    <path
                        d="M280 0C408.1 0 512 103.9 512 232c0 13.3-10.7 24-24 24s-24-10.7-24-24c0-101.6-82.4-184-184-184c-13.3 0-24-10.7-24-24s10.7-24 24-24zm8 192a32 32 0 1 1 0 64 32 32 0 1 1 0-64zm-32-72c0-13.3 10.7-24 24-24c75.1 0 136 60.9 136 136c0 13.3-10.7 24-24 24s-24-10.7-24-24c0-48.6-39.4-88-88-88c-13.3 0-24-10.7-24-24zM117.5 1.4c19.4-5.3 39.7 4.6 47.4 23.2l40 96c6.8 16.3 2.1 35.2-11.6 46.3L144 207.3c33.3 70.4 90.3 127.4 160.7 160.7L345 318.7c11.2-13.7 30-18.4 46.3-11.6l96 40c18.6 7.7 28.5 28 23.2 47.4l-24 88C481.8 499.9 466 512 448 512C200.6 512 0 311.4 0 64C0 46 12.1 30.2 29.5 25.4l88-24z" />
                </svg>
                <span class="espacio">Teléfonos</span>
            </div>
            <div id="copyright"><span>TlaCorp 2023</span></div>
            <div id="iconos">
                <svg class="icon-facebook" class="" xmlns="http://www.w3.org/2000/svg"
                        viewBox="0 0 320 512">
                        <path
                            d="M279.14 288l14.22-92.66h-88.91v-60.13c0-25.35 12.42-50.06 52.24-50.06h40.42V6.26S260.43 0 225.36 0c-73.22 0-121.08 44.38-121.08 124.72v70.62H22.89V288h81.39v224h100.17V288z" />
                </svg>
                <svg class="icon-instagram" xmlns="http://www.w3.org/2000/svg"
                        viewBox="0 0 448 512">
                        <path
                            d="M224.1 141c-63.6 0-114.9 51.3-114.9 114.9s51.3 114.9 114.9 114.9S339 319.5 339 255.9 287.7 141 224.1 141zm0 189.6c-41.1 0-74.7-33.5-74.7-74.7s33.5-74.7 74.7-74.7 74.7 33.5 74.7 74.7-33.6 74.7-74.7 74.7zm146.4-194.3c0 14.9-12 26.8-26.8 26.8-14.9 0-26.8-12-26.8-26.8s12-26.8 26.8-26.8 26.8 12 26.8 26.8zm76.1 27.2c-1.7-35.9-9.9-67.7-36.2-93.9-26.2-26.2-58-34.4-93.9-36.2-37-2.1-147.9-2.1-184.9 0-35.8 1.7-67.6 9.9-93.9 36.1s-34.4 58-36.2 93.9c-2.1 37-2.1 147.9 0 184.9 1.7 35.9 9.9 67.7 36.2 93.9s58 34.4 93.9 36.2c37 2.1 147.9 2.1 184.9 0 35.9-1.7 67.7-9.9 93.9-36.2 26.2-26.2 34.4-58 36.2-93.9 2.1-37 2.1-147.8 0-184.8zM398.8 388c-7.8 19.6-22.9 34.7-42.6 42.6-29.5 11.7-99.5 9-132.1 9s-102.7 2.6-132.1-9c-19.6-7.8-34.7-22.9-42.6-42.6-11.7-29.5-9-99.5-9-132.1s-2.6-102.7 9-132.1c7.8-19.6 22.9-34.7 42.6-42.6 29.5-11.7 99.5-9 132.1-9s102.7-2.6 132.1 9c19.6 7.8 34.7 22.9 42.6 42.6 11.7 29.5 9 99.5 9 132.1s2.7 102.7-9 132.1z" />
                </svg>
                <svg class="icon-skype" xmlns="http://www.w3.org/2000/svg"
                        viewBox="0 0 448 512">
                        <path
                            d="M424.7 299.8c2.9-14 4.7-28.9 4.7-43.8 0-113.5-91.9-205.3-205.3-205.3-14.9 0-29.7 1.7-43.8 4.7C161.3 40.7 137.7 32 112 32 50.2 32 0 82.2 0 144c0 25.7 8.7 49.3 23.3 68.2-2.9 14-4.7 28.9-4.7 43.8 0 113.5 91.9 205.3 205.3 205.3 14.9 0 29.7-1.7 43.8-4.7 19 14.6 42.6 23.3 68.2 23.3 61.8 0 112-50.2 112-112 .1-25.6-8.6-49.2-23.2-68.1zm-194.6 91.5c-65.6 0-120.5-29.2-120.5-65 0-16 9-30.6 29.5-30.6 31.2 0 34.1 44.9 88.1 44.9 25.7 0 42.3-11.4 42.3-26.3 0-18.7-16-21.6-42-28-62.5-15.4-117.8-22-117.8-87.2 0-59.2 58.6-81.1 109.1-81.1 55.1 0 110.8 21.9 110.8 55.4 0 16.9-11.4 31.8-30.3 31.8-28.3 0-29.2-33.5-75-33.5-25.7 0-42 7-42 22.5 0 19.8 20.8 21.8 69.1 33 41.4 9.3 90.7 26.8 90.7 77.6 0 59.1-57.1 86.5-112 86.5z" />
                </svg>
                <svg class="icon-linkedin" xmlns="http://www.w3.org/2000/svg" height="1.25em"
                        viewBox="0 0 448 512">
                        
                        <path
                            d="M100.28 448H7.4V148.9h92.88zM53.79 108.1C24.09 108.1 0 83.5 0 53.8a53.79 53.79 0 0 1 107.58 0c0 29.7-24.1 54.3-53.79 54.3zM447.9 448h-92.68V302.4c0-34.7-.7-79.2-48.29-79.2-48.29 0-55.69 37.7-55.69 76.7V448h-92.78V148.9h89.08v40.8h1.3c12.4-23.5 42.69-48.3 87.88-48.3 94 0 111.28 61.9 111.28 142.3V448z" />
                </svg>
                <svg class="icon-youtube" xmlns="http://www.w3.org/2000/svg" height="1.25em"
                        viewBox="0 0 576 512">
                        <path
                            d="M549.655 124.083c-6.281-23.65-24.787-42.276-48.284-48.597C458.781 64 288 64 288 64S117.22 64 74.629 75.486c-23.497 6.322-42.003 24.947-48.284 48.597-11.412 42.867-11.412 132.305-11.412 132.305s0 89.438 11.412 132.305c6.281 23.65 24.787 41.5 48.284 47.821C117.22 448 288 448 288 448s170.78 0 213.371-11.486c23.497-6.321 42.003-24.171 48.284-47.821 11.412-42.867 11.412-132.305 11.412-132.305s0-89.438-11.412-132.305zm-317.51 213.508V175.185l142.739 81.205-142.739 81.201z" />
                </svg>
            </div>
        </div>
    </body>

</html>

calendario/templates/pdf.html
<html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Calendario</title>
    <link rel="stylesheet" href="./static/css/pdf.css">
    <link rel="stylesheet" href="/static/css/pdf.css">
</head>
<body>
    {% block body %}{% endblock %}   
</body>
</html>