calendario/models/calendario.py
from main import db
from datetime import datetime, date, timedelta
from flask import current_app

class Calendario(db.Model):
    __tablename__ = "calendarios"
    id = db.Column(db.Integer, primary_key=True, autoincrement=False)
    fecha = db.Column(db.Date, nullable=False)
    ejercicio = db.Column(db.String(4), nullable=False)
    mes = db.Column(db.String(2), nullable=False)
    mes2 = db.Column(db.String(2), nullable=False)
    nombre_mes = db.Column(db.String(12), nullable=False)
    dia = db.Column(db.String(2), nullable=False)
    dia2 = db.Column(db.String(2), nullable=False)
    trimestre = db.Column(db.String(1), nullable=False)
    semana = db.Column(db.Integer, nullable=False)
    weekday = db.Column(db.Integer, nullable=False)
    festivocom = db.relationship('Festivocom', backref='calendariocom', lazy=False)
    festivoloc = db.relationship('Festivoloc', backref='calendarioloc', lazy=False)
    #asientos2 = db.relationship("Gasto", backref="user_gasto")

    def __init__(self, fecha, ejercicio,mes,mes2, nombre_mes,dia,dia2,trimestre,semana, weekday) -> None:
            
            fecha_referencia = date.fromisoformat("2024-01-01")
            
            self.id = (fecha - fecha_referencia).days +1
            self.fecha = fecha
            self.ejercicio = ejercicio
            self.mes = mes
            self.mes2 = mes2
            self.dia = dia
            self.dia2 = dia2
            self.trimestre = trimestre
            self.nombre_mes = nombre_mes
            self.semana = semana
            self.weekday = weekday
        
    def __repr__(self) -> str:
        return f'Calendarios: {self.fecha}'

calendario/models/comunidad.py
from main import db

class Comunidad(db.Model):
    __tablename__ = "comunidads"
    id = db.Column(db.Integer, primary_key=True, autoincrement=False)
    nombre = db.Column(db.String(100), nullable=False)
    descripcion = db.Column(db.String(300), nullable=True)
    localidades = db.relationship("Localidad", backref="comunidad", cascade="all, delete-orphan")
    festivocom = db.relationship('Festivocom', backref='comunidad', uselist=False)

    def __init__(self,id, nombre, descripcion) -> None:
            
            self.id = id
            self.nombre = nombre
            self.descripcion = descripcion
        
    def __repr__(self) -> str:
        return f'Localidad: {self.nombre}'

calendario/models/empresa.py
from main import db

class Empresa(db.Model):
    __tablename__ = "empresas"
    id = db.Column(db.Integer, primary_key=True, autoincrement=False)
    nombre = db.Column(db.String(150), nullable=False)
    domicilio = db.Column(db.String(150), nullable=False)
    actividad = db.Column(db.String(150), nullable=False)
    convenio = db.Column(db.String(150), nullable=False)
    centro = db.Column(db.String(150), nullable=False)
    localidad_id = db.Column(db.Integer, db.ForeignKey('localidads.id'), nullable=False)
    #id_localidad = db.Column(db.Integer, db.ForeignKey('localidad.id'), nullable=False)

    def __init__(self, id, nombre, domicilio,actividad,convenio, centro, localidad_id) -> None:
            
            self.id = id
            self.nombre = nombre
            self.domicilio = domicilio
            self.actividad = actividad
            self.convenio = convenio
            self.centro = centro
            self.localidad_id = localidad_id
            
    def __repr__(self) -> str:
        return f'Empresa: {self.nombre}'

calendario/routes.py
from flask import(render_template, Blueprint, flash, g, redirect, request, session,url_for,send_file,Response,make_response)
from werkzeug.utils import secure_filename
from dateutil import parser
from user.models.user import User
from calendario.models.empresa import Empresa
from calendario.models.calendario import Calendario
from calendario.models.comunidad import Comunidad
from calendario.models.localidad import Localidad
from calendario.models.festivocom import Festivocom
from calendario.models.festivoloc import Festivoloc
from sqlalchemy.orm import aliased

from sqlalchemy import text, func, and_ , or_

from reportlab.lib import colors
from fpdf import FPDF
from io import BytesIO

from user.routes import login_required
from datetime import date, timedelta, datetime
import calendar
from main import db, app
import os, json
import locale
import pandas as pd
from forms import fempresas
from forms import fcalendario

calendario = Blueprint('calendario', __name__, template_folder='templates', url_prefix='/calendario')

lang_code =  'es'

@calendario.route('/calendarios')
def calendarios():
    return redirect(url_for('index'))

@calendario.route('/')
@login_required
def inicio():
    
    # Comprobamos si hay calendario
    calendario = Calendario.query.count()
    empresas = Empresa.query.count()
    comunidades = Comunidad.query.count()
    localidades = Localidad.query.count()
    festivocom = Festivocom.query.count()
    festivoloc = Festivoloc.query.count()

    form = fcalendario()

    if calendario > 0:
        datos = {'calendario' : calendario,'empresas':empresas,'comunidades':comunidades,'localidades':localidades,'festivocom':festivocom,'festivoloc':festivoloc}
    else:
        datos = {'calendario' : calendario,'empresas':empresas,'comunidades':comunidades,'localidades':localidades,'festivocom':festivocom,'festivoloc':festivoloc}

    return render_template('calendario/inicio.html',datos = datos,form=form)

@calendario.route('/comunidad/<id>')
@login_required
def comunidad(id):
    localidades = Localidad.query.filter(Localidad.comunidad_id == id)
    comunidad = Comunidad.query.get(id)
    return render_template('calendario/comunidad.html',localidades = localidades, comunidad = comunidad)

@calendario.route('/empresa_cal/<empresa_id>')
@login_required
def empresa_cal(empresa_id):
    empresa = Empresa.query.get(empresa_id)
    loc = empresa.localidad_id
    com = empresa.localidad.comunidad_id
    festivoscom = Festivocom.query.filter(Festivocom.comunidad_id == com).all()
    festivosloc = Festivoloc.query.filter(Festivoloc.localidad_id == loc)
    mitadc = len(festivoscom) // 2
    com_iz = festivoscom[:mitadc+1]
    com_de = festivoscom[mitadc+1:]
    datos = [get_calendar(1,2024,loc,com),get_calendar(2,2024,loc,com),get_calendar(3,2024,loc,com),
             get_calendar(4,2024,loc,com),get_calendar(5,2024,loc,com),get_calendar(6,2024,loc,com),
             get_calendar(7,2024,loc,com),get_calendar(8,2024,loc,com),get_calendar(9,2024,loc,com),
             get_calendar(10,2024,loc,com),get_calendar(11,2024,loc,com),get_calendar(12,2024,loc,com)]
    return render_template('calendario/empresa_cal.html',com_iz=com_iz,com_de=com_de,empresa = empresa,datos=datos,festivoscom=festivoscom,festivosloc=festivosloc)

@calendario.route('/comunidad')
@login_required
def comunidades():
    localidades = Localidad.query.order_by(Localidad.id).all()
    return render_template('calendario/comunidades.html',localidades = localidades)


@calendario.route('/empresa/<id>')
@login_required
def empresa(id):
    empresas = Empresa.query.filter(Empresa.localidad.has(Localidad.comunidad_id == id))
    comunidad = Comunidad.query.get(id)
    return render_template('calendario/empresa.html',empresas = empresas, comunidad = comunidad)

@calendario.route('/empresas')
def empresas():
    #return "Enlace correcto"
    empresas = Empresa.query.all()

    return render_template('calendario/empresas.html',empresas=empresas)

@calendario.route('/festcom/')
@login_required
def festcom():
    festivoscomunitarios = Festivocom.query.all()
    if festivoscomunitarios:
        meses = ('enero','febrero','marzo','abril','mayo','junio','julio','agosto','septiembre','octubre','noviembre','diciembre')
        cal = {'enero':get_calendar(1,2024,11,10),'febrero':get_calendar(2,2024,11,10),'marzo':get_calendar(3,2024,11,10),
            'abril':get_calendar(4,2024,11,10),'mayo':get_calendar(5,2024,11,10),'junio':get_calendar(6,2024,11,10),
            'julio':get_calendar(7,2024,11,10),'agosto':get_calendar(8,2024,11,10),'septiembre':get_calendar(9,2024,11,10),
            'octubre':get_calendar(10,2024,11,10),'noviembre':get_calendar(11,2024,11,10),'diciembre':get_calendar(12,2024,11,10)}
        #print(cal['febrero'])
    else:
        festivoscomunitarios, meses, cal = '','',''
    return render_template('calendario/festcom.html',festivoscomunitarios = festivoscomunitarios,meses=meses,cal = cal)

# Lista de días festivos por localidades
@calendario.route('/festloc')
@login_required
def festloc():
    festivoslocales = Festivoloc.query.all()
    if festivoslocales:
        meses = ('enero','febrero','marzo','abril','mayo','junio','julio','agosto','septiembre','octubre','noviembre','diciembre')
        cal = {'enero':get_calendar(1,2024,11,10),'febrero':get_calendar(2,2024,11,10),'marzo':get_calendar(3,2024,11,10),
            'abril':get_calendar(4,2024,11,10),'mayo':get_calendar(5,2024,11,10),'junio':get_calendar(6,2024,11,10),
            'julio':get_calendar(7,2024,11,10),'agosto':get_calendar(8,2024,11,10),'septiembre':get_calendar(9,2024,11,10),
            'octubre':get_calendar(10,2024,11,10),'noviembre':get_calendar(11,2024,11,10),'diciembre':get_calendar(12,2024,11,10)}
    else:
        festivoslocales, meses, cal = '','',''
    return render_template('calendario/festloc.html',festivoslocales = festivoslocales,meses=meses,cal = cal)


@calendario.route('/dias/',methods = ['POST'])
@login_required
def dias():
    form = fcalendario()
    year = request.form['year']
    
    #locale.setlocale(locale.LC_TIME, 'es_ES')
    fecha_inicial = year + "-01-01"
    fecha_final = year + "-12-31"
    fecha_inicial_obj = date.fromisoformat(fecha_inicial)
    fecha_final_obj = date.fromisoformat(fecha_final)

    # Verifica que la fecha inicial sea anterior a la fecha final
    if fecha_inicial_obj > fecha_final_obj:
        return "Error: La fecha inicial debe ser anterior a la fecha final."

    # Genera una lista de todas las fechas correlativas dentro del rango especificado
    all_dates = []
    current_date = fecha_inicial_obj
    while current_date <= fecha_final_obj:
        fecha = str(current_date)
        fecha2 = parser.parse(fecha)  # Convierte la cadena de fecha a un objeto datetime
        weekday = fecha2.weekday()
        semana = fecha2.isocalendar()[1]
        ejercicio = fecha[0:4]
        mes = fecha[5:7]
        mes2 = str(current_date.month)
        nombre_mes = str(calendar.month_name[current_date.month])
        dia = fecha[8:]
        dia2 = str(current_date.day)
        if mes in ['01','02','03']:
            trimestre = "1"
        elif mes in ['04','05','06']:
            trimestre = '2'
        elif mes in ['07','08','09']:
            trimestre = '3'
        else:
            trimestre = '4'
        all_dates.append(Calendario(fecha=current_date, ejercicio=ejercicio, mes=mes,mes2=mes2,nombre_mes= nombre_mes, dia=dia, dia2=dia2, trimestre=trimestre, semana = semana, weekday = weekday))
        current_date += timedelta(days=1)

    # Inserta las fechas en la tabla de la base de datos
    db.session.bulk_save_objects(all_dates)
    db.session.commit()

    return f"Se generaron y almacenaron {len(all_dates)} días correlativos en la base de datos."

def resumen_excel():
    data = 'calendario/static/excel/calendario.xlsx'
    ruta = 'calendario/static/excel'
    fichero = 'calendario.xlsx'

    ruta_archivo = os.path.join(app.root_path, ruta, fichero)

    if os.path.exists(ruta_archivo):

        empresas = pd.read_excel(data,sheet_name="Empresas", names=['Empresa','Domicilio','Actividad','Convenio','Centro','Localidad'])
        empresas[['localidad_id', 'localidad']] = empresas['Localidad'].str.split('-', expand=True)
        empresas = empresas.fillna('')
        emp = len(empresas)

        localidades = pd.read_excel(data,sheet_name="Localidades")
        localidades.columns = ['id','localidad','cod_localidad','cod_comunidad','descripcion']
        localidades[['comunidad_id', 'comunidad']] = localidades['cod_comunidad'].str.split('-', expand=True)
        localidades = localidades.fillna('')
        loc = len(localidades)
        
        fesloc = pd.read_excel(data,sheet_name="Festivos_Localidades")
        fesloc.columns = ['id','fecha','nombre','descripcion','id_localidad']
        fesloc[['localidad_id', 'localidad']] = fesloc['id_localidad'].str.split('-', expand=True)
        fesloc = fesloc.fillna('')
        floc = len(fesloc)

        fescom = pd.read_excel(data,sheet_name="Festivos_Comunidades")
        fescom.columns = ['id','fecha','nombre','descripcion','id_comunidad']
        fescom[['comunidad_id', 'comunidad']] = fescom['id_comunidad'].str.split('-', expand=True)
        fescom = fescom.fillna('')
        fcom = len(fescom)

        resumen = {'fcom':fcom,'floc':floc,'loc':loc,'emp':emp}
    else: 
        resumen = {'fcom':0,'floc':0,'loc':0,'emp':0}
    return resumen

@calendario.route('/datos/',methods = ['GET','POST'])
def datos():
    if request.method == 'POST':
        fichero = request.files['fichero']
        if fichero:
            form = fempresas()
            
            # Hacer algo con el archivo, por ejemplo, guardarlo en el servidor
            filepath = os.path.abspath('calendario/static/excel/calendario.xlsx')
            fichero.save(filepath)

            resumen = resumen_excel()

calendario/templates/calendario/comunidad.html
{% extends 'base.html' %}

{% block rside %}
<h5 class="rside-cab">Empresas</h5>
<h5 class="rside-cab2">Tabla de localidades en {{comunidad.nombre}}</h5>
<div class="">
  <table class="table">
      <tr>
          <th>id.</th>
          <th>Localidad</th>
          <th>Comunidad</th>
          <th></th>
      </tr>
      {% for localidad in localidades %}
      <tr>
          <td>{{ localidad.id }}</td>
          <td>{{ localidad.nombre}}</td>
          <td>{{ localidad.comunidad.nombre }}</td>
          <td></td>
      </tr>
      {% endfor %}
  </table>
</div>
{% endblock %}

calendario/templates/calendario/comunidades.html
{% extends 'base.html' %}

{% block rside %}
<h5 class="rside-cab">Empresas</h5>
<h5 class="rside-cab2">Tabla de localidades</h5>
<div class="">
  <table class="table">
      <tr>
          <th>id.</th>
          <th>Localidad</th>
          <th>Comunidad</th>
          <th></th>
      </tr>
      {% for localidad in localidades %}
      <tr>
          <td>{{ localidad.id }}</td>
          <td>{{ localidad.nombre}}</td>
          <td>{{ localidad.comunidad.nombre }}</td>
          <td></td>
      </tr>
      {% endfor %}
  </table>
</div>
{% endblock %}

calendario/templates/calendario/datos.html
{% extends 'base.html' %}
{% block rside %}
<h5 class="rside-cab">Configuración</h5>
<h5 class="rside-cab2">Importación de datos</h5>
<div class="">
    {{resumen}}
    <h3>Tabla Empresas</h3>
        <h4>
            Número de empresas: {% if emp %} {{ emp | safe }} {% else %} No existe el excel
        </h4>
        <h3>Tabla Localidades</h3>
        <h4>
            Número de localidade: {% if loc %}  {{ loc | safe }} {% else %} No existe el excel
        </h4>
        <h3>Tabla Festivos comunidades</h3>
        <h4>
            Número de festivos: {% if fcom %} {{ fcom | safe }} {% else %} No existe el excel
        </h4>
        <h3>Tabla Festivos locales</h3>
        <h4>
            Número de festivos: {% if floc %} {{ floc | safe }} {% else %} No existe el excel
        </h4>
        <div><a href="#">Importar</a></div>
</div>
{% endblock %}

calendario/templates/calendario/datosform.html
{% extends 'base.html' %}
{% block rside %}
<h5 class="rside-cab">Configuración</h5>
<h5 class="rside-cab2">Importación de datos</h5>
<div class="">
    <form action="{{ url_for('calendario.datos')}}" method="POST" enctype="multipart/form-data">
        {{ form.csrf_token }}
        <div class="row">
            <div class="col-4 mb-2">
                {{form.fichero.label }}
                {{ form.fichero(class_="",placeholder="Fichero") }}
            </div>                     
            <div class="col-1 mb-2 ">
                <br>
                {{ form.submit(class="calbutton",style="width:100%") }}
            </div>
        </div>
    </form>
    <div class="">
        
        <h3>Tabla Empresas</h3>
        <h4>
            Número de empresas: {% if resumen %} {{ resumen.emp | safe }} {% else %} No existe el excel {% endif %}
        </h4>
        <h3>Tabla Localidades</h3>
        <h4>
            Número de localidade: {% if resumen %}  {{ resumen.loc | safe }} {% else %} No existe el excel {% endif %}
        </h4>
        <h3>Tabla Festivos comunidades</h3>
        <h4>
            Número de festivos: {% if resumen %} {{ resumen.fcom | safe }} {% else %} No existe el excel {% endif %}
        </h4>
        <h3>Tabla Festivos locales</h3>
        <h4>
            Número de festivos: {% if resumen %} {{ resumen.floc | safe }} {% else %} No existe el excel {% endif %}
        </h4>
        <div><a href="{{url_for('calendario.datos_import')}}">Importar</a></div>
    </div>
</div>
{% endblock %}

calendario/templates/calendario/empresa.html
{% extends 'base.html' %}
{% block rside %}
<h5 class="rside-cab">Empresas</h5>
<h5 class="rside-cab2">Tabla de empresas</h5>
<div class="">
  <table class="table">
      <tr>
          <th>id.</th>
          <th>Empresa</th>
          <th>Convenio</th>
          <th>Centro</th>
          <th>Localidad</th>
          <th></th>
          <th></th>
      </tr>
      {% for empresa in empresas %}
      <tr>
          <td>{{ empresa.id }}</td>
          <td><a href="{{ url_for('calendario.empresa_cal',empresa_id=empresa.id)}}">{{ empresa.nombre}}</a></td>
          <td>{{ empresa.convenio}}</td>
          <td>{{ empresa.centro }}</td>
          <td>{{ empresa.localidad.nombre }}</td>
          <td>
            <a href="">
                <svg xmlns="http://www.w3.org/2000/svg" height="16" viewBox="0 0 448 512">
                    <path d="M128 0c17.7 0 32 14.3 32 32V64H288V32c0-17.7 14.3-32 32-32s32 14.3 32 32V64h48c26.5 0 48 21.5 48 48v48H0V112C0 85.5 21.5 64 48 64H96V32c0-17.7 14.3-32 32-32zM0 192H448V464c0 26.5-21.5 48-48 48H48c-26.5 0-48-21.5-48-48V192zm64 80v32c0 8.8 7.2 16 16 16h32c8.8 0 16-7.2 16-16V272c0-8.8-7.2-16-16-16H80c-8.8 0-16 7.2-16 16zm128 0v32c0 8.8 7.2 16 16 16h32c8.8 0 16-7.2 16-16V272c0-8.8-7.2-16-16-16H208c-8.8 0-16 7.2-16 16zm144-16c-8.8 0-16 7.2-16 16v32c0 8.8 7.2 16 16 16h32c8.8 0 16-7.2 16-16V272c0-8.8-7.2-16-16-16H336zM64 400v32c0 8.8 7.2 16 16 16h32c8.8 0 16-7.2 16-16V400c0-8.8-7.2-16-16-16H80c-8.8 0-16 7.2-16 16zm144-16c-8.8 0-16 7.2-16 16v32c0 8.8 7.2 16 16 16h32c8.8 0 16-7.2 16-16V400c0-8.8-7.2-16-16-16H208zm112 16v32c0 8.8 7.2 16 16 16h32c8.8 0 16-7.2 16-16V400c0-8.8-7.2-16-16-16H336c-8.8 0-16 7.2-16 16z"/>
                </svg>
            </a>
        </td>
          <td></td>
      </tr>
      {% endfor %}
  </table>
</div>
{% endblock %}

calendario/templates/calendario/empresa_cal.html
{% extends 'base.html' %}
{% block rside %}
<h5 class="rside-cab">Empresas</h5>
<h5 class="rside-cab2">Calendario laboral - {{empresa.nombre}} ({% if empresa.centro %}{{empresa.centro}} - {% endif %}{{empresa.localidad.nombre}}) </h5>
<div id="empresa" style="margin-left:25px">
    <div><span>Dirección: </span><span>{{empresa.domicilio}}</span></div>
    <div><span>Actividad: </span><span>{{empresa.actividad}}</span></div>
    <div><span>Convenio: </span><span>{{empresa.convenio}}</span></div>
</div>
<div style="margin-left:25px;margin-top:20px;font-weight: 600;">Festivos {% if festivoscom[0] %}{{festivoscom[0].comunidad.nombre}}{% endif %}</div>
<div style="margin-left:25px;display: flex;width:100%" id="festivos">
    <div>
        <ul>
            {% for fcom in com_iz %}
            <li>{{ fcom.calendariocom.dia }} {{fcom.calendariocom.mes}} - {{ fcom.nombre }}</li>  
            {% endfor %}
        </ul>
    </div>
    <div>
        <ul>
            {% for fcom in com_de %}
            <li>{{ fcom.calendariocom.dia }} {{fcom.calendariocom.mes}} - {{ fcom.nombre }}</li>  
            {% endfor %}
        </ul>
    </div>
</div>
<div style="margin-left:25px;margin-top:20px;font-weight: 600;">Festivos {% if festivosloc[0] %}{{festivosloc[0].localidad.nombre}}{% endif %}</div>
<div style="margin-left:25px;width:100%" id="festivos">
    <div>
        <ul>
            {% for floc in festivosloc %}
            <li>{{ floc.calendarioloc.dia }} {{floc.calendarioloc.mes}} - {{ floc.nombre }}</li>  
            {% endfor %}
        </ul>
    </div>
</div>

<div style="width:100%;text-align: center;margin-top:20px;">
    <span style="font-size: 22px;">Descargar calendario </span>
    <a href="{{ url_for('calendario.calendario_anual',ejercicio='2024',localidad_id=empresa.localidad_id,empresa=empresa.id)}}" target="_blank"><svg xmlns="http://www.w3.org/2000/svg" height="22" viewBox="0 0 448 512">
        <path d="M128 0c17.7 0 32 14.3 32 32V64H288V32c0-17.7 14.3-32 32-32s32 14.3 32 32V64h48c26.5 0 48 21.5 48 48v48H0V112C0 85.5 21.5 64 48 64H96V32c0-17.7 14.3-32 32-32zM0 192H448V464c0 26.5-21.5 48-48 48H48c-26.5 0-48-21.5-48-48V192zm64 80v32c0 8.8 7.2 16 16 16h32c8.8 0 16-7.2 16-16V272c0-8.8-7.2-16-16-16H80c-8.8 0-16 7.2-16 16zm128 0v32c0 8.8 7.2 16 16 16h32c8.8 0 16-7.2 16-16V272c0-8.8-7.2-16-16-16H208c-8.8 0-16 7.2-16 16zm144-16c-8.8 0-16 7.2-16 16v32c0 8.8 7.2 16 16 16h32c8.8 0 16-7.2 16-16V272c0-8.8-7.2-16-16-16H336zM64 400v32c0 8.8 7.2 16 16 16h32c8.8 0 16-7.2 16-16V400c0-8.8-7.2-16-16-16H80c-8.8 0-16 7.2-16 16zm144-16c-8.8 0-16 7.2-16 16v32c0 8.8 7.2 16 16 16h32c8.8 0 16-7.2 16-16V400c0-8.8-7.2-16-16-16H208zm112 16v32c0 8.8 7.2 16 16 16h32c8.8 0 16-7.2 16-16V400c0-8.8-7.2-16-16-16H336c-8.8 0-16 7.2-16 16z"/>
        </svg>
    </a>
</div>
<div id="cal-year-cont" style="margin-top:20px;">
    {% for month in datos %}
    <div id="cal-month-cont">
        <div id="cal-month-cont">
            <div id="cal-month-cab">
                <div>{{month.resultado[15].nombre_mes}}</div>
                <div>2024</div>
            </div>
            <div id="cal-month-names">
                <div class="cal-month-name">lu</div>
                <div class="cal-month-name">ma</div>
                <div class="cal-month-name">mie</div>
                <div class="cal-month-name">ju</div>
                <div class="cal-month-name">vi</div>
                <div class="cal-month-name">sa</div>
                <div class="cal-month-name">do</div>
            </div>
            <div id="cal-month-days">
                {% for day in month.resultado %}
                <div class="cal-month-day 
                {% if day.weekday == 6 and not day.festivocom_nombre and not day.festivoloc_nombre %} 
                    domingo 
                {% endif %} 
                {% if day.festivoloc_nombre %} 
                    festivoloc 
                {% endif %} 
                {% if day.festivocom_nombre %} 
                    festivocom 
                {% endif %}">
                    {{ day.dia }}
                </div>
                {% endfor %}
            </div>
            <div>
            
        </div>
        </div>
    </div>
    {% endfor %}  
</div>
{% endblock %}

calendario/templates/calendario/empresasform.html
{% extends 'base.html' %}
{% block rside %}
<h5 class="rside-cab">Empresas</h5>
<h5 class="rside-cab2">Fichero Excel</h5>
<div class="">
    <form action="{{ url_for('calendario.importarexcel')}}" method="POST" enctype="multipart/form-data">
        {{ form.csrf_token }}
        <div class="row">
            <div class="col-4 mb-2">
                {{form.fichero.label }}
                {{ form.fichero(class_="",placeholder="Fichero") }}
            </div>                     
            <div class="col-1 mb-2 ">
                <br>
                {{ form.submit(class="calbutton",style="width:100%") }}
            </div>
        </div>
    </form>
</div>
{% endblock %}

calendario/templates/calendario/festcom.html
{% extends 'base.html' %}
{% block rside %}
<h5 class="rside-cab">Festivos de Comunidades Autónomas</h5>
<h5 class="rside-cab2">Tabla de días festivos</h5>
  <table class="table">
      <tr>
          <th>id.</th>
          <th>Fecha</th>
          <th>Festividad</th>
          <th>Comunidad</th>
          <th></th>
          <th></th>
      </tr>
      {% for festivo in festivoscomunitarios %}
      <tr>
          <td>{{ festivo.id }}</td>
          <td>{{ festivo.fecha}}</td>
          <td>{{ festivo.nombre}}</td>
          <td>{{ festivo.comunidad.nombre }}</td>
          <td></td>
          <td></td>
      </tr>
      {% endfor %}
  </table>
  <div id="separador"></div>
</div>
{% endblock %}

calendario/templates/calendario/inicio.html
{% extends 'base.html' %}

{% block rside %}
<h5 class="rside-cab">Calendario laboral</h5>
<h5 class="rside-cab2">Inicio</h5>
<div class="">
    {% if datos.calendario == 0 %}

    <div>Aún no existe un calendario. Debes crear uno para continuar.</div>
    <form action="{{ url_for('calendario.dias')}}" method="POST" enctype="multipart/form-data">
        {{ form.csrf_token }}
        <div class="row">
            <div class="col-4 mb-2">
                {{form.year.label }}
                {{ form.year(class_="",placeholder="Año") }}
            </div>
            <div class="col-1 mb-2 ">
                <br>
                {{ form.submit(class="calbutton",style="width:100%") }}
            </div>
        </div>
    </form>
    {% else %}
    <div>
        <div>Comunidades autónomas</div>
        <div>{{ datos.comunidades }}</div>
    </div>
    <div>
        <div>Localidades</div>
        <div>{{ datos.localidades }}</div>
    </div>
    <div>
        <div>Empresas</div>
        <div>{{ datos.empresas }}</div>
    </div>
    <div>
        <div>Festivos Comunidades</div>
        <div>{{ datos.festivocom }}</div>
    </div>
    <div>
        <div>Festivos Localidades</div>
        <div>{{ datos.festivoloc }}</div>
    </div>
    <div></div>
    {% endif %}
</div>
{% endblock %}